apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-microservice
  name: frontend-microservice-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/frontend-microservice-svc
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: frontend-microservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
